#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql 
dbc_sql_substitutions=1
dbc_generate_include=template:/etc/hackradio/dbsettings.py
dbc_generate_include_args=-otemplate_infile=/usr/share/hackradio/debian/dbsettings.py.template
dbc_generate_include_owner=root:www-data
dbc_generate_include_perms=0640
dbc_go hackradio $@

if [ "$1" = configure ] ; then
    random_key=$( env LANG=C LC_ALL=C tr -dc "[:alnum:]" < /dev/urandom | dd bs=1 count=63 2> /dev/null )
    tempfile=`tempfile`
    sed -e "s/__SECRET_KEY__/$random_key/" < /usr/share/hackradio/debian/settings.py.template > $tempfile
    chown root:www-data $tempfile
    chmod 0640 $tempfile
    ucf --debconf-ok $tempfile /etc/hackradio/settings.py
    ucfr hackradio /etc/hackradio/settings.py 
    rm -f $tempfile

    chown -R www-data:www-data /var/log/hackradio
    chown -R www-data:www-data /var/lib/hackradio
    chown -R www-data:www-data /var/cache/hackradio

    usermod --append --groups audio www-data

    su --shell /bin/bash --login www-data --command "/usr/share/hackradio/manage.py migrate"

   if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
       . /usr/share/apache2/apache2-maintscript-helper
       apache2_invoke enmod wsgi || exit $?
    fi
    # dh_apache2 a2enmod wsgi
    # dh_apache2 a2enconf hackradio
fi

#DEBHELPER#
