# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=4096, verbose_name='name')),
                ('disk_path', models.CharField(max_length=4096, unique=True, verbose_name='disk_path')),
                ('selected', models.BooleanField(default=False, verbose_name='selected')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jukebox.Folder')),
            ],
            options={
                'ordering': ['parent', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('skipped', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.Folder')),
            ],
            options={
                'ordering': ['folder', 'filename'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('folder', 'filename')]),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([('parent', 'name')]),
        ),
    ]
