# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='convertable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='converted_path',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
