# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0002_auto_20161013_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
