# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0002_auto_20161004_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='selectable',
            field=models.BooleanField(default=False, verbose_name='selectable'),
        ),
    ]
