# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from jukebox.models import Collection, Folder

def insert_legacy_collection(apps, schema_editor):
    legacy = Collection(name="Legacy", disk_path="")
    legacy.save()

    Folder.objects.all().update(collection=legacy)

def remove_legacy_collection(apps, schema_editor):
    Folder.objects.all().update(collection=-1)
    Collection.objects.filter(name="Legacy", disk_path="").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0004_auto_20161014_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('disk_path', models.CharField(max_length=4096, verbose_name='disk_path')),
            ],
        ),
        migrations.AlterField(
            model_name='folder',
            name='disk_path',
            field=models.CharField(db_index=True, max_length=4096, verbose_name='disk_path'),
        ),
        migrations.AddField(
            model_name='folder',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='jukebox.Collection'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='folder',
            index_together=set([('selected', 'order'), ('collection', 'disk_path')]),
        ),
        migrations.RunPython(
            insert_legacy_collection, remove_legacy_collection
        ),
    ]
